const Data = [
  {
    id: 0,
    image: "../images/sketchershoes1.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 1,
    image: "../images/sketchershoes2.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 2,
    image: "../images/sketchershoes3.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 3,
    image: "../images/sketchershoes4.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 4,
    image: "../images/sketchershoes5.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 5,
    image: "../images/sketchershoes6.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 6,
    image: "../images/sketchershoes7.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 7,
    image: "../images/sketchershoes8.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 8,
    image: "../images/sketchershoes9.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 9,
    image: "../images/sketchershoes10.png",
    desc: "Sketcher Branded Shoes",
    price: "100$",
    category: "sketcher",
  },
  {
    id: 10,
    image: "../images/nikeshoes1.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
  {
    id: 11,
    image: "../images/nikeshoes2.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
  {
    id: 12,
    image: "../images/nikeshoes3.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
  {
    id: 13,
    image: "../images/nikeshoes4.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
  {
    id: 14,
    image: "../images/nikeshoes5.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
  {
    id: 15,
    image: "../images/nikeshoes6.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
  {
    id: 16,
    image: "../images/nikeshoes7.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
  {
    id: 7,
    image: "../images/nikeshoes8.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
  {
    id: 8,
    image: "../images/nikeshoes9.png",
    desc: "Nike Branded Shoes",
    price: "100$",
    category: "Nike",
  },
];

export default Data;
